[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.128.2"      # pick a current version you use locally
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
